### ISSUE TITLE
Ghidra 11.2 not yet supported

### ISSUE THREAD

**Issue by Aypahyo** [yetmorecode/ghidra-lx-loader#8]
**Executable used**
Which EXE are you trying to load? Can it be found somewhere for testing?
Orion2.exe
https://store.steampowered.com/app/410980/Master_of_Orion_2/

**Ghidra**
Which Ghidra version are you using?
Version 11.2
Build PUBLIC
2024-Sep-26 1444 EDT
JAve Version 21.0.4

**ghidra-lx-loader**
Version used: 10.2

**Describe the bug**
What's wrong?

'void ghidra.app.util.bin.BinaryReader.setPointerIndex(int)'
java.lang.NoSuchMethodError: 'void ghidra.app.util.bin.BinaryReader.setPointerIndex(int)'
	at yetmorecode.ghidra.lx.loader.LeLoader.checkFormat(LeLoader.java:37)
	at yetmorecode.ghidra.lx.LinearLoader.findSupportedLoadSpecs(LinearLoader.java:79)
	at ghidra.app.util.opinion.LoaderService.getSupportedLoadSpecs(LoaderService.java:47)
	at ghidra.app.util.opinion.LoaderService.getAllSupportedLoadSpecs(LoaderService.java:71)
	at ghidra.plugin.importer.ImporterUtilities.showImportSingleFileDialog(ImporterUtilities.java:287)
	at ghidra.plugin.importer.ImporterUtilities.showImportDialog(ImporterUtilities.java:154)
	at ghidra.plugin.importer.ImporterUtilities.lambda$showImportDialog$0(ImporterUtilities.java:106)
	at ghidra.util.task.TaskLauncher$2.run(TaskLauncher.java:115)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Ubuntu 21.0.4
OS: Linux 6.8.0-48-generic amd64

---------------------------------------------------

The Bug stems from a not supported ghidra version

https://ghidra.re/ghidra_docs/api/ghidra/app/util/bin/BinaryReader.html#setPointerIndex(int)

It is unclear to me why this method would not be found. It seems unchanged.

**Comment by mduggan** [comment]
You can fix this by rebuilding the plugin for the latest Ghidra, eg:
```
gradle -PGHIDRA_INSTALL_DIR=/Full/path/to/your/ghidra
```
then use `File->Install Extensions` to add the zip file that gets created in `dist`

**Comment by yetmorecode** [comment]
Added new release for 12.0.1
